#!/usr/bin/env python3
"""Regenerate sources/cut_the_knot.yaml from the problem entries.

Every Cut-the-Knot URL cited as a primary or additional source is listed
together with the entries that cite it.  Run after adding entries:

    python scripts/build_sources.py
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import REPO_ROOT, load_all_entries  # noqa: E402

OUT_PATH = REPO_ROOT / "sources" / "cut_the_knot.yaml"

HEADER = {
    "name": "Cut-the-Knot",
    "home": "https://www.cut-the-knot.org/",
    "author": "Alexander Bogomolny (1948-2018)",
    "description": (
        "Interactive Mathematics Miscellany and Puzzles. Pages were located by "
        "crawling the Games and Puzzles index (games.shtml, gamesList.shtml), the "
        "Proofs index (proofs/index.shtml), the Things Impossible index "
        "(impossible/index.shtml) and the related-material links on the invariant "
        "pages. All URLs below returned HTTP 200 on the access date."
    ),
    "accessed": "2026-09-16",
    "license_note": (
        "Only URLs and short problem summaries in our own words are stored; "
        "no page text is copied."
    ),
}


def main() -> int:
    pages: dict[str, dict] = defaultdict(lambda: {"title": None, "cited_by": []})
    for entry in load_all_entries():
        cited = [("primary", entry["source"])]
        cited += [("additional", s) for s in (entry.get("additional_sources") or [])]
        for role, src in cited:
            url = str(src.get("url") or "")
            if "cut-the-knot.org" not in url:
                continue
            rec = pages[url]
            if src.get("original_title") and not rec["title"]:
                rec["title"] = src["original_title"]
            rec["cited_by"].append({"id": entry["id"], "role": role})

    out = {
        "source": HEADER,
        "pages": [
            {"url": u, "title": pages[u]["title"], "cited_by": pages[u]["cited_by"]}
            for u in sorted(pages)
        ],
    }
    with OUT_PATH.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Cut-the-Knot pages used by this repository.\n")
        fh.write("# Generated by scripts/build_sources.py; do not edit by hand.\n")
        yaml.safe_dump(out, fh, sort_keys=False, allow_unicode=True, width=100)
    print(f"Wrote {len(pages)} Cut-the-Knot pages to {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
