#!/usr/bin/env python3
"""Print a Markdown summary of the repository.

    python scripts/summarize_repository.py            # print to stdout
    python scripts/summarize_repository.py --write    # also write docs/SUMMARY.md

Reports: total number of problems, counts per idea category (leaf and root),
per source, number from Cut-the-Knot, famous vs. less famous, and coverage
of mathematical domains.
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import REPO_ROOT, load_all_entries, load_taxonomy  # noqa: E402

SUMMARY_PATH = REPO_ROOT / "docs" / "SUMMARY.md"


def table(title: str, counter: Counter, label: str) -> list[str]:
    lines = [f"### {title}", "", f"| {label} | Count |", "|---|---:|"]
    for key, n in sorted(counter.items(), key=lambda kv: (-kv[1], str(kv[0]))):
        lines.append(f"| {key} | {n} |")
    lines.append("")
    return lines


def build_summary() -> str:
    taxonomy = load_taxonomy()
    entries = load_all_entries()
    total = len(entries)

    by_leaf = Counter(e["key_idea"]["category"] for e in entries)
    by_root = Counter(taxonomy[e["key_idea"]["category"]]["root"] for e in entries)
    by_folder = Counter(e["_folder"] for e in entries)
    by_source = Counter(e["source"]["name"] for e in entries)
    by_domain = Counter(e["problem"].get("domain", "unspecified") for e in entries)

    ctk_main = sum(1 for e in entries if "cut-the-knot" in e["source"]["name"].lower())
    ctk_any = sum(
        1 for e in entries
        if "cut-the-knot" in e["source"]["name"].lower()
        or any("cut-the-knot" in (s.get("name") or "").lower() for s in (e.get("additional_sources") or []))
    )
    famous = sum(1 for e in entries if e.get("familiarity", {}).get("famous"))
    widely = sum(1 for e in entries if e.get("familiarity", {}).get("likely_widely_known"))
    high_all = sum(
        1 for e in entries
        if all(v == "high" for v in e.get("quality", {}).values())
    )

    lines = ["# Repository summary", "", "_Generated by `scripts/summarize_repository.py`._", ""]
    lines += ["## Totals", ""]
    lines += [f"- Total problems: **{total}**"]
    lines += [f"- Problems whose primary source is Cut-the-Knot: **{ctk_main}**"]
    lines += [f"- Problems citing Cut-the-Knot as primary or additional source: **{ctk_any}**"]
    lines += [f"- Distinct primary sources: **{len(by_source)}**"]
    lines += [f"- Famous problems: **{famous}**; less famous: **{total - famous}**"]
    lines += [f"- Likely widely known: **{widely}**; likely less known: **{total - widely}**"]
    lines += [f"- Entries rated `high` on all four quality labels: **{high_all}**"]
    lines += [f"- Idea categories used (leaf level): **{len(by_leaf)}** of {len(taxonomy)} in the taxonomy"]
    lines += [""]

    root_named = Counter({f"{k} ({taxonomy[k]['name']})": v for k, v in by_root.items()})
    lines += table("Problems per top-level idea category", root_named, "Category")
    leaf_named = Counter({f"{k} ({taxonomy[k]['name']})": v for k, v in by_leaf.items()})
    lines += table("Problems per idea category (leaf)", leaf_named, "Category")
    lines += table("Problems per folder", by_folder, "Folder")
    lines += table("Problems per primary source", by_source, "Source")
    lines += table("Coverage of mathematical domains", by_domain, "Domain")

    lines += ["### Unused taxonomy categories", ""]
    unused = [k for k in taxonomy if k not in by_leaf]
    lines += [", ".join(f"`{k}`" for k in unused) if unused else "_none_", ""]

    lines += ["## Entry list", "", "| id | title | category | source | famous |", "|---|---|---|---|---|"]
    for e in sorted(entries, key=lambda e: (e["_folder"], e["id"])):
        rel = e["_path"].relative_to(REPO_ROOT).as_posix()
        fam = "yes" if e.get("familiarity", {}).get("famous") else "no"
        lines.append(f"| [{e['id']}]({rel}) | {e['title']} | {e['key_idea']['category']} | {e['source']['name']} | {fam} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write docs/SUMMARY.md as well as printing")
    args = ap.parse_args()
    text = build_summary()
    print(text)
    if args.write:
        SUMMARY_PATH.write_text(text, encoding="utf-8", newline="\n")
        print(f"\nWrote {SUMMARY_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
