"""Population replacement game (seed: the three-colour chameleon problem).

Structure: ``vector_game`` with k classes, a conserved total N and a small
set of move vectors. Question: can a single-class state be reached?

Canonical idea: a linear form alpha . x (mod m) that every move leaves
unchanged and that takes a different value on the initial state than on every
target state.

Novel instances are generated by choosing (m, alpha) first and then sampling
move vectors from the kernel of alpha (mod m), so a modular invariant always
exists; ground truth is exact BFS over the conserved-total state space, and
unreachable instances that the canonical invariant does *not* separate are
rejected (they would be impossible for a different reason).

Transfer surfaces:
    d0  the classical 13 / 15 / 17 chameleons
    d1  coloured tokens with explicit "remove ... add ..." operations
    d2  commutative string rewriting over a small alphabet (same structure,
        different representation)
"""
from __future__ import annotations

import random
import re
from itertools import product
from typing import Optional

from ..extraction.json_block import find_certificates
from ..structures import vector_game as vg
from ..utils.hashing import derive_seed
from .base import CanonicalIdea, ExtractedCertificate, Instance, ProblemFamily, register_family

SURFACES = {0: "classical_chameleons", 1: "coloured_tokens", 2: "string_rewriting"}
COLOUR_POOL = ["red", "green", "blue", "yellow", "purple", "orange", "white", "black", "grey", "pink", "brown", "silver"]
LETTER_POOL = list("pqstuvwxyz")


def _plural(n: int, noun: str) -> str:
    return f"{n} {noun}" + ("" if n == 1 else "s")


def _signed_rep(a: int, m: int) -> int:
    """Representative of a mod m in (-m/2, m/2] for readable prose."""
    a %= m
    return a - m if a > m / 2 else a


def _sentence_span(text: str, start: int, end: int) -> tuple[int, int]:
    s = start
    while s > 0 and text[s - 1] not in ".!?\n":
        s -= 1
    e = end
    while e < len(text) and text[e] not in ".!?\n":
        e += 1
    return s, min(len(text), e + 1)


@register_family
class PopulationGameFamily(ProblemFamily):
    family_id = "population_game"
    idea_type = "modular_invariant"
    domain = "combinatorial processes / invariants"
    size_parameter = "total population N (state space ~ N^(k-1))"
    certificate_type = "modular_invariant"
    certificate_types = ("modular_invariant", "explicit_construction")
    verification_method = "local_rule"
    generation_method = "seeded (modulus, form) then kernel-sampled moves; exact BFS ground truth; rejection sampling"
    supported_transfer_levels = (0, 1, 2)
    version = "0.1"

    def __init__(self, possible_fraction: float = 0.35, n_classes: int = 3, moduli=(3, 4, 5), min_nonzero_coefficients: int = 2, max_attempts: int = 2000):
        self.possible_fraction = possible_fraction
        self.n_classes = n_classes
        self.moduli = tuple(moduli)
        self.min_nonzero_coefficients = min_nonzero_coefficients
        self.max_attempts = max_attempts

    # -- generation ------------------------------------------------------
    def _ground_truth(self, structure: dict, canonical: dict) -> dict:
        reachable, path, n_states = vg.reachability(structure)
        if reachable:
            witness = {"certificate_type": "explicit_construction", "moves": [i + 1 for i in path]}
            return {"answer": "possible", "proof_type": "explicit_construction", "witness": witness, "n_states_explored": n_states, "canonical_invariant": canonical}
        alpha, m = canonical["coefficients"], canonical["modulus"]
        phi0 = vg.linear_form(alpha, structure["initial"], m)
        separated = all(vg.linear_form(alpha, t, m) != phi0 for t in structure["targets"])
        return {
            "answer": "impossible",
            "proof_type": "modular_invariant" if separated else "other",
            "witness": None,
            "n_states_explored": n_states,
            "canonical_invariant": canonical,
        }

    @staticmethod
    def _kernel_moves(alpha: tuple[int, ...], m: int, k: int, max_entry: int = 3) -> list[list[int]]:
        out = []
        for v in product(range(-max_entry, max_entry + 1), repeat=k):
            if sum(v) != 0 or all(x == 0 for x in v):
                continue
            if min(v) >= 0 or max(v) <= 0:
                continue
            if vg.linear_form(alpha, v, m) != 0:
                continue
            out.append(list(v))
        return out

    def generate_instance(self, size: int, seed: int, answer: Optional[str] = None, **kwargs) -> Instance:
        k = self.n_classes
        if size < 2 * k:
            raise ValueError(f"size must be >= {2 * k}")
        rng = random.Random(derive_seed(self.family_id, self.version, size, seed))
        want_possible = (rng.random() < self.possible_fraction) if answer is None else (answer == "possible")
        colours = rng.sample(COLOUR_POOL, k)
        for _ in range(self.max_attempts):
            m = rng.choice(self.moduli)
            alpha = tuple(rng.randrange(m) for _ in range(k))
            if len(set(alpha)) == 1 or sum(a != 0 for a in alpha) < self.min_nonzero_coefficients:
                continue  # zero / conservation forms are never decision-relevant; single-class counts are too easy
            kernel = self._kernel_moves(alpha, m, k)
            if len(kernel) < 2:
                continue
            n_moves = rng.randint(2, min(4, len(kernel)))
            moves = rng.sample(kernel, n_moves)
            # every class must be consumable by some move, otherwise the game is degenerate
            if any(all(v[i] >= 0 for v in moves) for i in range(k)):
                continue
            cuts = sorted(rng.sample(range(1, size), k - 1))
            initial = [b - a for a, b in zip([0] + cuts, cuts + [size])]
            structure = vg.make_structure(colours, moves, initial, vg.single_class_targets(k, size), "all objects of a single class")
            canonical = {"certificate_type": "modular_invariant", "coefficients": list(alpha), "modulus": m}
            gt = self._ground_truth(structure, canonical)
            if want_possible and gt["answer"] == "possible":
                break
            if not want_possible and gt["proof_type"] == "modular_invariant":
                break
        else:  # pragma: no cover
            raise RuntimeError(f"could not generate a {'possible' if want_possible else 'impossible'} instance of size {size}")
        return Instance(
            instance_id=f"{self.family_id}-n{size}-s{seed}-d1",
            family_id=self.family_id,
            size=size,
            transfer_level=1,
            generation_seed=seed,
            structure=structure,
            parameters={"n_classes": k, "n_moves": len(moves), "modulus": m, "total": size},
            ground_truth=gt,
            idea_bearing=gt["answer"] == "impossible",
            surface={"type": SURFACES[1], "class_names": colours, "noun": "token"},
            transfer={"level": 1, "source_family": self.family_id, "target_surface": SURFACES[1], "preserved_structure": "vector game with a modular linear invariant", "transformation": "seeded (modulus, form) and kernel-sampled moves"},
            family_version=self.version,
        )

    def classical_instance(self) -> Instance:
        colours = ["red", "green", "blue"]
        moves = [[-1, -1, 2], [-1, 2, -1], [2, -1, -1]]
        structure = vg.make_structure(colours, moves, [13, 15, 17], vg.single_class_targets(3, 45), "all chameleons of a single colour")
        canonical = {"certificate_type": "modular_invariant", "coefficients": [1, 2, 0], "modulus": 3}
        gt = self._ground_truth(structure, canonical)
        return Instance(
            instance_id=f"{self.family_id}-classical-chameleons-d0",
            family_id=self.family_id,
            size=45,
            transfer_level=0,
            generation_seed=0,
            structure=structure,
            parameters={"n_classes": 3, "n_moves": 3, "modulus": 3, "total": 45, "name": "chameleons 13/15/17"},
            ground_truth=gt,
            idea_bearing=True,
            surface={"type": SURFACES[0], "class_names": colours, "noun": "chameleon"},
            transfer={"level": 0, "source_family": self.family_id, "target_surface": SURFACES[0], "preserved_structure": "vector game with a modular linear invariant", "transformation": "none (classical seed problem)"},
            source="classical",
            family_version=self.version,
        )

    def apply_surface(self, instance: Instance, transfer_level: int, seed: int) -> Instance:
        if transfer_level != 2:
            raise ValueError(f"{self.family_id} supports surface change only at level 2")
        rng = random.Random(derive_seed(self.family_id, "surface", transfer_level, seed, instance.instance_id))
        letters = rng.sample(LETTER_POOL, vg.dimension(instance.structure))
        new_id = instance.instance_id[: -len("-d1")] + "-d2" if instance.instance_id.endswith("-d1") else instance.instance_id + "-d2"
        return Instance(
            instance_id=new_id,
            family_id=self.family_id,
            size=instance.size,
            transfer_level=2,
            generation_seed=seed,
            structure=instance.structure,
            parameters=dict(instance.parameters),
            ground_truth=instance.ground_truth,
            idea_bearing=instance.idea_bearing,
            surface={"type": SURFACES[2], "class_names": letters, "noun": "letter"},
            transfer={
                "level": 2,
                "source_family": self.family_id,
                "source_instance_id": instance.instance_id,
                "target_surface": SURFACES[2],
                "preserved_structure": "vector game with a modular linear invariant",
                "transformation": "classes -> letters of an alphabet; operations -> commutative rewriting rules; states -> multisets of letters",
            },
            source=instance.source,
            family_version=self.version,
        )

    # -- rendering -------------------------------------------------------
    def _names(self, instance: Instance) -> list[str]:
        return list(instance.surface.get("class_names") or instance.structure["classes"])

    def _describe_move(self, move: list[int], names: list[str], noun: str) -> str:
        removed = [_plural(-v, f"{n} {noun}") for v, n in zip(move, names) if v < 0]
        added = [_plural(v, f"{n} {noun}") for v, n in zip(move, names) if v > 0]
        return f"remove {' and '.join(removed)}, and add {' and '.join(added)}"

    def render_problem(self, instance: Instance, format: str = "text") -> str:
        surface = instance.surface.get("type", SURFACES[instance.transfer_level])
        s = instance.structure
        names = self._names(instance)
        total = vg.total(s)
        if surface == SURFACES[0]:
            return (
                "On an island there are 13 red, 15 green and 17 blue chameleons. Whenever two chameleons of different colours meet, "
                "they both change to the third colour (for example, a red and a green chameleon meeting both become blue). "
                "Is it possible that after some sequence of such meetings all 45 chameleons have the same colour?"
            )
        if surface == SURFACES[1]:
            counts = ", ".join(_plural(c, f"{n} token") for c, n in zip(s["initial"], names))
            ops = "\n".join(f"  Operation {i + 1}: {self._describe_move(mv, names, 'token')}." for i, mv in enumerate(s["moves"]))
            return (
                f"A box contains {total} tokens. Each token has one of {len(names)} colours: {', '.join(names)}. "
                f"Initially the box contains {counts}. The following operations may be performed any number of times, in any order, "
                f"as long as enough tokens of the required colours are present:\n{ops}\n\n"
                f"Is it possible, by some sequence of these operations, to reach a situation in which all {total} tokens in the box have the same colour?"
            )
        if surface == SURFACES[2]:
            counts = ", ".join(f"{c} occurrences of {n}" for c, n in zip(s["initial"], names))
            rules = []
            for i, mv in enumerate(s["moves"]):
                lhs = " ".join(n for v, n in zip(mv, names) for _ in range(-v) if v < 0)
                rhs = " ".join(n for v, n in zip(mv, names) for _ in range(v) if v > 0)
                rules.append(f"  Rule {i + 1}: {lhs} -> {rhs}")
            return (
                f"Consider words over the alphabet {{{', '.join(names)}}}. Letters may be freely reordered, so a word is determined by how many "
                f"times each letter occurs. Start from the word of length {total} with {counts}. A rewriting rule may be applied whenever every "
                f"letter on its left-hand side occurs in the current word (with multiplicity); it deletes those letters and inserts the letters on "
                f"its right-hand side. The rules are:\n" + "\n".join(rules) + "\n\n"
                f"Is it possible, by some sequence of rule applications, to reach a word in which only one distinct letter occurs?"
            )
        raise ValueError(f"unknown surface {surface!r}")

    # -- mathematics -----------------------------------------------------
    def solve_ground_truth(self, instance: Instance) -> dict:
        return self._ground_truth(instance.structure, instance.ground_truth["canonical_invariant"])

    def _form_prose(self, coefficients, m: int, names: list[str]) -> str:
        terms = []
        for a, n in zip(coefficients, names):
            a = _signed_rep(a, m)
            if a == 0:
                continue
            sign = "-" if a < 0 else "+"
            mag = "" if abs(a) == 1 else f"{abs(a)} * "
            terms.append((sign, f"{mag}(number of {n})"))
        text = ""
        for i, (sign, term) in enumerate(terms):
            text += (("-" if sign == "-" else "") if i == 0 else f" {sign} ") + term
        return text

    def canonical_idea(self, instance: Instance) -> CanonicalIdea:
        canon = instance.ground_truth["canonical_invariant"]
        names = self._names(instance)
        m = canon["modulus"]
        prose = (
            f"Consider the quantity {self._form_prose(canon['coefficients'], m, names)}, taken modulo {m}. Every allowed operation changes this "
            f"quantity by a multiple of {m}, so its remainder modulo {m} never changes. Compare its value in the initial state with its value in "
            f"each state that has only one class present; if they differ, that state can never be reached."
        )
        cert = {"certificate_type": "modular_invariant", "coefficients": {n: _signed_rep(a, m) for a, n in zip(canon["coefficients"], names)}, "modulus": m}
        return CanonicalIdea(prose, cert, "modular_invariant", f"linear invariant mod {m}", prose)

    def alternative_idea(self, instance: Instance) -> Optional[CanonicalIdea]:
        canon = instance.ground_truth["canonical_invariant"]
        s = instance.structure
        m, k = canon["modulus"], vg.dimension(s)
        names = self._names(instance)
        phi_alpha = tuple(canon["coefficients"])
        for beta in vg.kernel_vectors_mod(s["moves"], m, k):
            if any(tuple((lam * a) % m for a in phi_alpha) == beta for lam in range(1, m)):
                continue
            phi0 = vg.linear_form(beta, s["initial"], m)
            if all(vg.linear_form(beta, t, m) != phi0 for t in s["targets"]):
                prose = f"Consider the quantity {self._form_prose(beta, m, names)} modulo {m}; it is unchanged by every operation."
                cert = {"certificate_type": "modular_invariant", "coefficients": {n: _signed_rep(a, m) for a, n in zip(beta, names)}, "modulus": m}
                return CanonicalIdea(prose, cert, "modular_invariant", f"alternative linear invariant mod {m}", prose)
        return None

    def invalid_idea(self, instance: Instance) -> dict:
        s = instance.structure
        m = instance.ground_truth["canonical_invariant"]["modulus"]
        names = self._names(instance)
        for beta in product(range(m), repeat=vg.dimension(s)):
            if any(vg.linear_form(beta, mv, m) != 0 for mv in s["moves"]):
                return {"certificate_type": "modular_invariant", "coefficients": {n: b for b, n in zip(beta, names)}, "modulus": m}
        raise RuntimeError("no non-invariant form exists")  # pragma: no cover

    def canonical_match(self, instance: Instance, normalized_certificate: dict) -> bool:
        if normalized_certificate.get("certificate_type") != "modular_invariant":
            return False
        canon = instance.ground_truth["canonical_invariant"]
        m = canon["modulus"]
        alpha = [a % m for a in canon["coefficients"]]
        if normalized_certificate["form"] == "linear":
            if normalized_certificate["modulus"] != m:
                return False
            beta = normalized_certificate["coefficients"]
            return any([(lam * a) % m for a in alpha] == beta for lam in range(1, m))
        # expression form: same partition of the state space as the canonical form?
        from ..verifiers.modular_invariant import ModularInvariantVerifier

        s = instance.structure
        k, n = vg.dimension(s), vg.total(s)
        if vg.count_states(k, n) > 50_000:
            return False
        ver = ModularInvariantVerifier()
        mapping: dict = {}
        seen_values: set = set()
        for state in vg.enumerate_states(k, n):
            a = vg.linear_form(alpha, state, m)
            try:
                b = ver._phi(s, normalized_certificate, state)
            except Exception:  # noqa: BLE001
                return False
            if a in mapping:
                if mapping[a] != b:
                    return False
            else:
                if b in seen_values:
                    return False
                mapping[a] = b
                seen_values.add(b)
        return True

    # -- structured-output schemas (conditions B and C only) ---------------
    def certificate_schema_text(self, instance: Instance) -> str:
        names = self._names(instance)
        example = ", ".join(f'"{n}": <integer>' for n in names)
        op = "rule" if instance.surface.get("type") == SURFACES[2] else "operation"
        return (
            "Use exactly one of the following JSON schemas:\n"
            f'{{"certificate_type": "modular_invariant", "coefficients": {{{example}}}, "modulus": <integer>}}\n'
            "  - the claim: the sum of coefficient * (number of objects of that class), taken modulo the modulus, is unchanged by every\n"
            f"    {op}, and its value in the initial state differs from its value in every state with a single class present.\n"
            f'{{"certificate_type": "modular_invariant", "expr": "<expression in the class counts, e.g. ({names[0]} - {names[1]}) % 3>"}}\n'
            f'{{"certificate_type": "explicit_construction", "moves": [<{op} number>, ...]}}  - an explicit sequence of {op} numbers reaching the target.\n'
            '{"certificate_type": "none"}  - if no such principle was used.'
        )

    # -- deterministic extraction ------------------------------------------
    def _alias_regex(self, names: list[str]) -> tuple[str, dict[str, int]]:
        alias_to_idx: dict[str, int] = {}
        initials = [n[0].lower() for n in names]
        for i, n in enumerate(names):
            for alias in (n.lower(), n.lower() + "s", f"n_{n.lower()}", f"x_{n.lower()}", f"#{n.lower()}"):
                alias_to_idx[alias] = i
            if initials.count(n[0].lower()) == 1 and len(n) > 1:
                alias_to_idx[n[0].lower()] = i
                alias_to_idx[n[0].upper()] = i
        ordered = sorted(alias_to_idx, key=len, reverse=True)
        return "|".join(re.escape(a) for a in ordered), alias_to_idx

    def extract_candidates(self, instance: Instance, response: str) -> list[ExtractedCertificate]:
        out: list[ExtractedCertificate] = []
        for hit in find_certificates(response):
            if hit.obj.get("certificate_type") in self.certificate_types:
                out.append(ExtractedCertificate(hit.obj, hit.text, hit.start, hit.end, "json_block", "json_block"))
        names = self._names(instance)
        alias_re, alias_to_idx = self._alias_regex(names)
        k = len(names)
        noun = r"(?:\s+(?:tokens?|chameleons?|letters?|objects?|creatures?|counts?))?"
        name = rf"(?<![A-Za-z_#])({alias_re})(?![A-Za-z_])"
        # one term: [sign] [coef] [*] [(] [the] [number of] [#] NAME [noun] [)]
        term = rf"([+\-−]?)\s*(\d+)?\s*\*?\s*\(?\s*(?:the\s+)?(?:number\s+of\s+)?(?:#\s*)?{name}{noun}\s*\)?"
        linear = rf"\(?\s*{term}(?:\s*(?=[+\-−]){term})*\s*\)?"
        pattern = re.compile(rf"{linear}[^.\n;]{{0,30}}?(?:\(\s*)?(?:mod(?:ulo)?|%)\s*(\d+)", re.IGNORECASE)
        term_re = re.compile(term, re.IGNORECASE)
        mod_split = re.compile(r"\bmod\b|\bmodulo\b|%", re.IGNORECASE)
        seen: set[tuple] = set()
        for m in pattern.finditer(response):
            modulus = int(m.group(m.lastindex))
            if modulus < 2:
                continue
            coefficients = [0] * k
            body = mod_split.split(m.group(0), maxsplit=1)[0]
            for t in term_re.finditer(body):
                sign, num, alias = t.group(1), t.group(2), t.group(3)
                key = alias if alias in alias_to_idx else alias.lower()
                if key not in alias_to_idx:
                    continue
                coef = int(num) if num else 1
                if sign in ("-", "−"):
                    coef = -coef
                coefficients[alias_to_idx[key]] += coef
            if all(c % modulus == 0 for c in coefficients):
                continue
            key_t = (tuple(c % modulus for c in coefficients), modulus)
            if key_t in seen:
                continue
            seen.add(key_t)
            s, e = _sentence_span(response, m.start(), m.end())
            cert = {"certificate_type": "modular_invariant", "coefficients": {n: c for n, c in zip(names, coefficients)}, "modulus": modulus}
            out.append(ExtractedCertificate(cert, response[s:e], s, e, "deterministic:linear_form_mod", "linear_form_mod"))
        diff_re = re.compile(rf"difference\s+(?:between|of)\s+(?:the\s+)?(?:numbers?\s+of\s+)?{name}{noun}\s+and\s+(?:the\s+)?(?:number\s+of\s+)?{name}{noun}[^.\n]{{0,80}}?(?:mod(?:ulo)?|%)\s*(\d+)", re.IGNORECASE)
        for m in diff_re.finditer(response):
            a, b, modulus = m.group(1).lower(), m.group(2).lower(), int(m.group(3))
            if a not in alias_to_idx or b not in alias_to_idx or alias_to_idx[a] == alias_to_idx[b] or modulus < 2:
                continue
            coefficients = [0] * k
            coefficients[alias_to_idx[a]] += 1
            coefficients[alias_to_idx[b]] -= 1
            key_t = (tuple(c % modulus for c in coefficients), modulus)
            if key_t in seen:
                continue
            seen.add(key_t)
            s, e = _sentence_span(response, m.start(), m.end())
            cert = {"certificate_type": "modular_invariant", "coefficients": {n: c for n, c in zip(names, coefficients)}, "modulus": modulus}
            out.append(ExtractedCertificate(cert, response[s:e], s, e, "deterministic:difference_phrase", "difference_phrase"))
        return out
